[project]
name = "sip-server-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.12.4",
    "pydub>=0.25.1",
    "websockets>=15.0.1",
]

[tool.ruff.lint]
extend-select = ["I"]